/*
 * ultrasonic.c
 *
 *  Created on: Oct 22, 2021
 *      Author: lenovo
 */


#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

//global variables

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_timePeriod = 0;
uint16 g_timePeriodPlusHigh = 0;
uint8 flag = 0 ;


//description : This is the call back function called by the ICU driver.
//used to calculate the high time (pulse time) generated by the ultrasonic sensor.


void Ultrasonic_edgeProcessing(void)
{
	if (flag){
		g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);

			g_edgeCount = 0; //clear the number of edges
		}
	}

}



//description : function to 1.Initialize the ICU driver 2.Setup the ICU call back function. 3.
void Ultrasonic_init(void) {

	Icu_ConfigType Icu_Config = {F_CPU_8,RISING}; //frequency F_CPU/8 and to detect the raising edge as the first edge.

	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT); //Setup the direction for the trigger pin as output pin

	Icu_init(&Icu_Config) ;

	Icu_setCallBack(Ultrasonic_edgeProcessing);

}

//function to transmit  10 us trigger pulse to the HC-SR04 Trig Pin.

void Ultrasonic_Trigger() {

	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);

	_delay_us(10) ;

	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);

}

//description : Send the trigger pulse by using Ultrasonic_Trigger function.
//& Start the measurements by the ICU
//Inputs: None
// Return: The measured distance in Centimeter.

uint16 Ultrasonic_readDistance(void) {

	Ultrasonic_Trigger();

	flag = 1 ;

	uint16 distance = g_timeHigh / 57.9 ;

	return distance ;


}







